# Basic Information 
title: Vinny Adjibi
title_alt: Vinny Adjibi
position: Ph.D. Student
affiliation: Georgia Institute of Technology
email: vinny [dot] adjibi [at] gatech [dot] edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: vinny adjibi, boladji vinny adjibi, security researcher, DNS
description: This is my personal academic homepage where I keep track of my publication and research interests.
canonical: https://boladjivinny.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=Hqz6d7AAAAAJ&hl=en
cv_link: assets/files/resume.pdf
github_link: https://github.com/boladjivinny
linkedin: https://www.linkedin.com/in/boladjivinny

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/photo.jpg

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
